name = "rjc-film"
compatibility_date = "2026-08-29"

# This starter is Vite-based.
# Build command: npm run build
# Output directory: dist
[assets] 
directory="./dist"

[build]
command ="npm run build"
